### PR TITLE
event-scraper fails if  directory is missing, so this closes #6

### LINKED ISSUE #6: [bug] event-scraper fails if `data/events` directory is missing

### PR DESCRIPTION
**Pull request by amed**
Fixes #6

### CODE REVIEW

File: lib/events-scraper/utils.rb [hunk 1]
```diff
@@ -6,6 +6,7 @@
 WEBSITE = 'http://webmontag.de'
 FACEBOOK_URL = ''
 ROOT_DIR = File.expand_path("../../../", __FILE__)
+EVENTS_DIR = "#{ROOT_DIR}/data/events/"
```
Comment (jhilden) [inline lib/events-scraper/utils.rb]: the `EVENTS_DIR` constant is not used anywhere else besides the event class, so it does not make sense (yet) to extact it to a general "utils" file

**Review by jhilden — CHANGES_REQUESTED** [review]
